INSERT INTO "tbl_duty" ("name", "description") VALUES ('Chủ trì', 'Chủ trì');
INSERT INTO "tbl_duty" ("name", "description") VALUES ('Tham gia tích cực', 'Tham gia tích cực');
INSERT INTO "tbl_duty" ("name", "description") VALUES ('Tham gia', 'Tham gia');
INSERT INTO "tbl_duty" ("name", "description") VALUES ('Không tham gia', 'Không tham gia');
INSERT INTO "tbl_duty" ("name", "description") VALUES ('HCV Hội thao UTC', 'HCV Hội thao UTC');
INSERT INTO "tbl_duty" ("name", "description") VALUES ('HCB Hội thao UTC', 'HCB Hội thao UTC');
INSERT INTO "tbl_duty" ("name", "description") VALUES ('HCĐ Hội thao UTC', 'HCĐ Hội thao UTC');
INSERT INTO "tbl_duty" ("name", "description") VALUES ('Vận động viên', 'Vận động viên');
INSERT INTO "tbl_duty" ("name", "description") VALUES ('Vận động viên thi đấu giải UTC', 'Vận động viên thi đấu giải UTC');
INSERT INTO "tbl_duty" ("name", "description") VALUES ('Cổ động viên mức nhiệt tình', 'Cổ động viên mức nhiệt tình');
INSERT INTO "tbl_duty" ("name", "description") VALUES ('Cổ động viên mức tích cực', 'Cổ động viên mức tích cực');
INSERT INTO "tbl_duty" ("name", "description") VALUES ('Cổ động viên', 'Cổ động viên');
INSERT INTO "tbl_duty" ("name", "description") VALUES ('Vận động viên thi đấu giải cấp Bộ', 'Vận động viên thi đấu giải cấp Bộ');
INSERT INTO "tbl_duty" ("name", "description") VALUES ('HCV cấp Bộ GD&ĐT', 'HCV cấp Bộ GD&ĐT');
INSERT INTO "tbl_duty" ("name", "description") VALUES ('HCB cấp Bộ GD&ĐT', 'HCB cấp Bộ GD&ĐT');
INSERT INTO "tbl_duty" ("name", "description") VALUES ('HCĐ cấp Bộ GD&ĐT', 'HCĐ cấp Bộ GD&ĐT');
INSERT INTO "tbl_duty" ("name", "description") VALUES ('Tham gia họp', 'Tham gia họp');
INSERT INTO "tbl_duty" ("name", "description") VALUES ('Vắng có lý do', 'Vắng có lý do');
INSERT INTO "tbl_duty" ("name", "description") VALUES ('Vắng không lí do', 'Vắng không lí do');
INSERT INTO "tbl_duty" ("name", "description") VALUES ('Tác giả chính/Tác giả liên hệ', 'Tác giả chính/Tác giả liên hệ');
INSERT INTO "tbl_duty" ("name", "description") VALUES ('Tác giả tham gia', 'Tác giả tham gia');
INSERT INTO "tbl_duty" ("name", "description") VALUES ('Chủ biên', 'Chủ biên');
INSERT INTO "tbl_duty" ("name", "description") VALUES ('Tham gia viết', 'Tham gia viết');
INSERT INTO "tbl_duty" ("name", "description") VALUES ('Thành viên chính', 'Thành viên chính');
INSERT INTO "tbl_duty" ("name", "description") VALUES ('Thành viên tham gia', 'Thành viên tham gia');
