INSERT INTO "tbl_event" ("name", "description") VALUES ('Chương trình du xuân', 'Chương trình du xuân');
INSERT INTO "tbl_event" ("name", "description") VALUES ('Hoạt động chào mừng 8-3', 'Hoạt động chào mừng 8-3');
INSERT INTO "tbl_event" ("name", "description") VALUES ('Hoạt động tổng kết năm học', 'Hoạt động tổng kết năm học');
INSERT INTO "tbl_event" ("name", "description") VALUES ('Hoạt động chào mừng 20-10', 'Hoạt động chào mừng 20-10');
INSERT INTO "tbl_event" ("name", "description") VALUES ('Hoạt động hội thao Công đoàn trường', 'Hoạt động hội thao Công đoàn trường');
INSERT INTO "tbl_event" ("name", "description") VALUES ('Hoạt động văn nghệ', 'Hoạt động văn nghệ');
INSERT INTO "tbl_event" ("name", "description") VALUES ('Tổ chức gặp mặt hưu trí', 'Tổ chức gặp mặt hưu trí');
INSERT INTO "tbl_event" ("name", "description") VALUES ('Giải thể thao các trường ĐH-CĐ khu vực Hà Nội', 'Giải thể thao các trường ĐH-CĐ khu vực Hà Nội');
INSERT INTO "tbl_event" ("name", "description") VALUES ('Giải giao hữu các trường ĐH-CĐ khu vực Hà Nội', 'Giải giao hữu các trường ĐH-CĐ khu vực Hà Nội');
INSERT INTO "tbl_event" ("name", "description") VALUES ('Thi đấu thể thao giao lưu khoa tổ chức', 'Thi đấu thể thao giao lưu khoa tổ chức');
INSERT INTO "tbl_event" ("name", "description") VALUES ('Các cuộc họp do CĐ trường tổ chức', 'Các cuộc họp do CĐ trường tổ chức');
INSERT INTO "tbl_event" ("name", "description") VALUES ('Các cuộc họp do CĐ khoa tổ chức', 'Các cuộc họp do CĐ khoa tổ chức');
INSERT INTO "tbl_event" ("name", "description") VALUES ('Họp BCH Công đoàn khoa', 'Họp BCH Công đoàn khoa');
INSERT INTO "tbl_event" ("name", "description") VALUES ('Hoạt động hiếu - hỉ', 'Hoạt động hiếu - hỉ');
INSERT INTO "tbl_event" ("name", "description") VALUES ('Hoạt động từ thiện', 'Hoạt động từ thiện');
INSERT INTO "tbl_event" ("name", "description") VALUES ('Học tập nâng cao trình độ chuyên môn', 'Học tập nâng cao trình độ chuyên môn');
INSERT INTO "tbl_event" ("name", "description") VALUES ('Hoạt động đăng báo khoa học quốc tế CIE/A&HCI/SSCI', 'Hoạt động đăng báo khoa học quốc tế CIE/A&HCI/SSCI');
INSERT INTO "tbl_event" ("name", "description") VALUES ('Hoạt động đăng báo khoa học quốc tế ESCI', 'Hoạt động đăng báo khoa học quốc tế ESCI');
INSERT INTO "tbl_event" ("name", "description") VALUES ('Hoạt động đăng báo khoa học quốc tế Scopus', 'Hoạt động đăng báo khoa học quốc tế Scopus');
INSERT INTO "tbl_event" ("name", "description") VALUES ('Hoạt động đăng báo khoa học trong nước', 'Hoạt động đăng báo khoa học trong nước');
INSERT INTO "tbl_event" ("name", "description") VALUES ('Báo cáo hội thảo quốc tế', 'Báo cáo hội thảo quốc tế');
INSERT INTO "tbl_event" ("name", "description") VALUES ('Báo cáo hội thảo trong nước', 'Báo cáo hội thảo trong nước');
INSERT INTO "tbl_event" ("name", "description") VALUES ('Viết giáo trình', 'Viết giáo trình');
INSERT INTO "tbl_event" ("name", "description") VALUES ('Viết tài liệu tham khảo', 'Viết tài liệu tham khảo');
INSERT INTO "tbl_event" ("name", "description") VALUES ('Viết tài liệu chuyên khảo', 'Viết tài liệu chuyên khảo');
INSERT INTO "tbl_event" ("name", "description") VALUES ('Sáng chế và giải pháp hữu ích', 'Sáng chế và giải pháp hữu ích');
