CREATE TABLE "tbl_user"
(
    "id"              INTEGER      NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "email"           VARCHAR(64)  NOT NULL UNIQUE,
    "work_email"      VARCHAR(64) UNIQUE,
    "password"        VARCHAR(256) NOT NULL UNIQUE,
    "full_name"       VARCHAR(128) NOT NULL,
    "phone_number"    VARCHAR(16)  NOT NULL,
    "academic_rank"   VARCHAR(64),
    "academic_degree" VARCHAR(64),
    PRIMARY KEY ("id")
);

CREATE TABLE "tbl_user_role"
(
    "user_id" INTEGER NOT NULL,
    "role_id" INTEGER NOT NULL,
    PRIMARY KEY ("user_id", "role_id")
);

CREATE TABLE "tbl_role"
(
    "id"          INTEGER      NOT NULL,
    "name"        VARCHAR(32)  NOT NULL UNIQUE,
    "description" VARCHAR(128) NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "tbl_event"
(
    "id"          INTEGER      NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "name"        VARCHAR(128) NOT NULL UNIQUE,
    "description" VARCHAR(128) NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "tbl_duty"
(
    "id"          INTEGER      NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "name"        VARCHAR(64)  NOT NULL,
    "description" VARCHAR(128) NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "tbl_event_score"
(
    "event_id" INTEGER NOT NULL,
    "duty_id"  INTEGER NOT NULL,
    "score"    DECIMAL NOT NULL,
    PRIMARY KEY ("event_id", "duty_id")
);

CREATE TABLE "tbl_event_detail"
(
    "event_id"   INTEGER   NOT NULL,
    "user_id"    INTEGER   NOT NULL,
    "duty_id"    INTEGER   NOT NULL,
    "start_date" TIMESTAMP NOT NULL,
    "end_date"   TIMESTAMP NOT NULL,
    PRIMARY KEY ("event_id", "user_id", "duty_id")
);

ALTER TABLE "tbl_user_role"
    ADD FOREIGN KEY ("user_id") REFERENCES "tbl_user" ("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "tbl_user_role"
    ADD FOREIGN KEY ("role_id") REFERENCES "tbl_role" ("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "tbl_event_detail"
    ADD FOREIGN KEY ("user_id") REFERENCES "tbl_user" ("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "tbl_event_detail"
    ADD FOREIGN KEY ("event_id") REFERENCES "tbl_event" ("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "tbl_event_detail"
    ADD FOREIGN KEY ("duty_id") REFERENCES "tbl_duty" ("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "tbl_event_score"
    ADD FOREIGN KEY ("duty_id") REFERENCES "tbl_duty" ("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "tbl_event_score"
    ADD FOREIGN KEY ("event_id") REFERENCES "tbl_event" ("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;
